max_obstacle_height: 0.60 

robot_radius: 0.15 

obstacle_layer:
  enabled:              true
  max_obstacle_height:  0.6
  origin_z:             0.0
  z_resolution:         0.2
  z_voxels:             10
  unknown_threshold:    15
  mark_threshold:       0
  combination_method:   1
  track_unknown_space:  true   
  obstacle_range: 5.5
  raytrace_range: 6.0
  origin_z: 0.0
  publish_voxel_map: false
  observation_sources:  scan
  scan: {data_type: LaserScan, topic: kobuki/laser/scan, marking: true, clearing: true, inf_is_valid: true}
  
inflation_layer:
  enabled:              true
  cost_scaling_factor:  5.0
  inflation_radius:     0.4  

static_layer:
  enabled:              true
  

