global_costmap:
   global_frame: map
   robot_base_frame: base_footprint
   update_frequency: 0.1
   publish_frequency: 0.6
   transform_tolerance: 0.5

   plugins:
     - {name: static_layer,            type: "costmap_2d::StaticLayer"}
     - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}

