GlobalPlanner: 
  old_navfn_behavior: false 
  use_quadratic: true  
  use_grid_path: false                          
  
  allow_unknown: true 
                                              
  planner_window_x: 0.0   
  planner_window_y: 0.0         
  default_tolerance: 0.0                        
  
  publish_scale: 100  
  planner_costmap_publish_frequency: 0.0     
  
  lethal_cost: 253   
  neutral_cost: 50 

  publish_potential: true