shutdown_costmaps: false

max_planning_retries: 0
recovery_behavior_enabled: false

controller_frequency: 1.0
controller_patience: 30.0

planner_frequency: 0.0
planner_patience: 20.0

oscillation_timeout: 0.0
oscillation_distance: 0.2

base_local_planner: "dwa_local_planner/DWAPlannerROS"

base_global_planner: "navfn/NavfnROS"